hassansabbir/weather-cast

src/app/page.js
=> new branch sabbir

src/app/page.js
=> First commit from nizam

src/app/Components/Footer.jsx, src/app/Components/Navbar.jsx, src/app/layout.jsx
=> Naziya sultana mithila

next.config.js, src/app/(home)/ProductSection.jsx, src/app/(home)/page.jsx
=> product section added

src/app/about/page.jsx
Reverts hassansabbir/weather-cast#27
=> Revert "commit"

.eslintrc.json, package.json, src/Firebase/Firebase.config.js, src/Providers/AuthProvider.jsx, src/Providers/index.jsx, src/app/(home)/SimpleWeatherMap.jsx, src/app/(home)/page.jsx, src/app/Components/Navbar.jsx, src/app/contact/page.jsx, src/app/layout.jsx, src/app/logIn/page.jsx, src/app/signUp/page.jsx, src/hooks/useClient.js
=> error solving

src/app/(home)/SimpleWeatherMap.jsx, src/app/blog/page.jsx
=> error fixing

src/app/(home)/WeatherDetails/WeatherDetails.jsx, src/app/(home)/WeatherNews/WeatherNews.jsx
=> some change on home page

package.json, src/app/(home)/SimpleWeatherMap.jsx, src/app/(home)/WeatherDetails/WeatherDetails.jsx, src/app/(home)/WeatherNews/WeatherNews.jsx, src/app/(home)/WeatherUodates/WeatherUpdates.jsx, src/app/Components/Navbar.jsx, src/app/about/ourTeam/page.jsx, src/app/about/page.jsx, src/app/blog/page.jsx, src/app/logIn/page.jsx, src/app/signUp/page.jsx
responsiveness and navbar updated
=> responsiveness and navbar updated

src/app/(home)/page.jsx, src/app/(home)/reviews/Reviews.jsx, src/app/(home)/reviews/ShowReviews.jsx
=> reviews function updated

next.config.js, src/app/(home)/Articles.jsx, src/app/(home)/page.jsx
=> articles added

src/app/(home)/WeatherDetails/WeatherDetails.jsx
=> added celsius and fahrenheit btn

src/app/(home)/Intelligence.jsx
=> aos updated

src/Providers/AuthProvider.jsx, src/app/Components/SocialLogin.jsx, src/app/logIn/page.jsx, src/app/signUp/page.jsx
authentication updated with react-hook-form
=> authentication updated with react-hook-form

src/app/(home)/WeatherDetails/WeatherDetails.jsx, src/app/(home)/WeatherUodates/WeatherUpdates.jsx, src/app/blog/page.jsx, src/hooks/useAuth.js, src/routes/PrivetRoute.jsx
=> privet route added

next.config.js, src/app/Components/Navbar.jsx, src/app/profile/page.jsx
=> profile route created

next.config.js, package.json, src/app/(home)/CurrentWeather/CurrentWeather.jsx, src/app/(home)/CustomizeIcon/CustomizeIcon.jsx, src/app/(home)/FiveDayForecast/FiveDayForecast.jsx, src/app/(home)/HourlyChart/HourlyChart.jsx, src/app/(home)/TodayHighLights/TodayHighLights.jsx, src/app/(home)/WeatherDetails/WeatherDetails.jsx, src/app/(home)/WeatherLocation/WeatherLocation.jsx
=> rechart added

next.config.js, package.json, src/app/(home)/ProductSection.jsx, src/app/(home)/SimpleWeatherMap.jsx, src/app/(home)/WeatherDetails/WeatherDetails.jsx, src/app/(home)/WeatherUodates/WeatherAlert.jsx, src/app/(home)/WeatherUodates/WeatherUpdates.jsx, src/app/(home)/page.jsx, src/app/(home)/reviews/Reviews.jsx, src/app/Components/Footer.jsx, src/app/Components/Navbar.jsx, src/app/articles/[id]/page.jsx, src/app/articles/page.jsx, src/app/blog/page.jsx, src/app/dashboard/Sidebar.jsx, src/app/dashboard/favorite-location/page.jsx, src/app/dashboard/layout.jsx, src/app/dashboard/manage-user/page.jsx, src/app/dashboard/page.jsx, src/app/layout.jsx, src/app/news/page.jsx, src/routes/PrivetRoute.jsx
dashboard & articles page added
=> dashboard & articles page added

package.json, src/app/(home)/WeatherUodates/WeatherUpdates.jsx, src/app/details/HumidityChart.jsx, src/app/details/PressureChart.jsx, src/app/details/ThreeHourWeather/ThreeHourWeather.jsx, src/app/details/WeatherDetails/WeatherDetails.jsx, src/app/details/WindChart.jsx, src/app/details/page.jsx
=> added chart

src/app/details/HumidityChart.jsx, src/app/details/PressureChart.jsx, src/app/details/WeatherDetails/WeatherDetails.jsx, src/app/details/WindChart.jsx, src/app/details/weatherCharts/WeatherCharts.jsx
=> added some design in chart

src/app/dashboard/manage-user/page.jsx, src/utils/getWeatherIcon.jsx
=> manage user updated

src/app/(home)/WeatherUodates/WeatherUpdates.css, src/app/(home)/WeatherUodates/WeatherUpdates.jsx
=> weather update

src/app/dashboard/Sidebar.jsx, src/app/dashboard/manage-user/page.jsx
=> dashboard updated

package.json, src/app/contact/page.jsx
Email js implemented in contact page by Nizam.
=> Implementation of Email js in contact page completed

src/app/dashboard/my-articles/page.jsx
=> articles updated

src/app/details/WeatherDetails/WeatherDetails.jsx
=> change server side live link

src/app/details/HourlyForcast/HourlyForcast.jsx
commit with updateing forecast
=> commit with updateing forecast

src/app/articles/[id]/page.jsx, src/app/articles/page.jsx, src/app/dashboard/manage-articles/page.jsx
=> manage articles added

src/app/dashboard/my-articles/page.jsx
=> article status updated

package.json, src/app/details/HourlyForcast/HourlyForcast.jsx
=> chart updated

src/app/(home)/WeatherNews/WeatherNews.jsx, src/app/(home)/WeatherUodates/WeatherUpdates.jsx, src/app/articles/[id]/page.jsx, src/app/articles/page.jsx, src/app/news/page.jsx
=> responsive

src/app/contact/page.jsx
Update code added in contact page
=> Update code added in contact page

src/app/(home)/Banner.jsx
commit with animation with banner
=> commit with animation with banner

src/app/(home)/WeatherUodates/WeatherUpdates.jsx
commit with polishing background
=> commit with polishing background

src/app/details/HourlyForcast/HourlyForcast.jsx
=> react tab add

src/app/Components/Navbar.jsx
=> commit with polishing navbvar

src/app/Components/footer/Footer.jsx, src/app/dashboard/layout.jsx, src/app/layout.jsx
Montserrat font added globally
=>  Montserrat font added globally

src/app/(home)/community/Donation/page.jsx
commit with polishing donation
=> commit with polishing donation

src/app/(home)/community/Donation/page.jsx
=> commit with donation 2nd part

src/app/(home)/community/Donation/page.jsx
=> donation form

src/app/articles/add-articles/page.jsx
Image hosting added in article page.
=> Image hosting added in article page

src/app/details/HourlyForcast/HourlyForcast.css, src/app/details/HourlyForcast/HourlyForcast.jsx
=> table updated

src/app/Components/Navbar.jsx, src/app/dashboard/Sidebar.jsx, src/app/dashboard/layout.jsx, src/app/dashboard/user-home/page.jsx
=> modify some design

src/app/dashboard/dashboard-pagination/page.jsx, src/app/dashboard/manage-user/page.jsx
=> user pagination added
